# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etransfer.proto\"+\n\x0bLendRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x12\x0c\n\x04\x62\x61nk\x18\x02 \x01(\x05\"\"\n\x0cLendResponse\x12\x12\n\nlendAccept\x18\x01 \x01(\x08\x32=\n\x0f\x42\x61nkInteraction\x12*\n\tLendMoney\x12\x0c.LendRequest\x1a\r.LendResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transfer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LENDREQUEST._serialized_start=18
  _LENDREQUEST._serialized_end=61
  _LENDRESPONSE._serialized_start=63
  _LENDRESPONSE._serialized_end=97
  _BANKINTERACTION._serialized_start=99
  _BANKINTERACTION._serialized_end=160
# @@protoc_insertion_point(module_scope)
