# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transfer_pb2 as transfer__pb2


class BankInteractionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LendMoney = channel.unary_unary(
                '/BankInteraction/LendMoney',
                request_serializer=transfer__pb2.LendRequest.SerializeToString,
                response_deserializer=transfer__pb2.LendResponse.FromString,
                )


class BankInteractionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LendMoney(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankInteractionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LendMoney': grpc.unary_unary_rpc_method_handler(
                    servicer.LendMoney,
                    request_deserializer=transfer__pb2.LendRequest.FromString,
                    response_serializer=transfer__pb2.LendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BankInteraction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BankInteraction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LendMoney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BankInteraction/LendMoney',
            transfer__pb2.LendRequest.SerializeToString,
            transfer__pb2.LendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
